### ISSUE TITLE
requirements.txt problem

### ISSUE THREAD

**Issue by dididadawd** [aruancaf/stock-trading-bot#17]
C:\stock-trading-bot-master>pip3 install -r requirements.txt
Collecting alpaca-trade-api==0.53.0
  Using cached alpaca_trade_api-0.53.0-py3-none-any.whl (36 kB)
Collecting beautifulsoup4==4.9.3
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting certifi==2020.12.5
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting numpy==1.20.1
  Using cached numpy-1.20.1.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error

**Comment by aoberai** [comment]
Have you ever been able to install numpy? - pip3 install numpy

**Comment by dididadawd** [comment]
This is the first time that I try

**Comment by dididadawd** [comment]
Is the version of NumPy is important?

**Comment by dididadawd** [comment]
I succedded, but 
"when installing the dependencies I get the following error:

The conflict is caused by:
The user requested websockets==9.1
alpaca-trade-api 0.53.0 depends on websockets<9 and >=8.0"
the same result like him

**Comment by dididadawd** [comment]
I was trying anything it doesn't work.

**Comment by aoberai** [comment]
Pull the new code, have pushed the fix

**Comment by dididadawd** [comment]
ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
I think that it is because python 3.10 should I change the version of python?

**Comment by aoberai** [comment]
Perhaps, current requirements.txt works for me.

**Comment by dididadawd** [comment]
I checked it on another device and it worked

**Comment by dididadawd** [comment]
I was able to run it on docker but there I encountered another error
Traceback (most recent call last):
  File "runner.py", line 65, in <module>
    alpaca = alp.Alpaca()
  File "/alpaca.py", line 8, in __init__
    self.account  = self.api.get_account()
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 184, in get_account
    resp = self.get('/account')
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 162, in get
    return self._request('GET', path, data)
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 125, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 154, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: request is not authorized

**Comment by dkoak** [comment]
> @dididadawd did you find a solution to this problem?

**Comment by aoberai** [comment]
Did you get yourself new alpaca api keys and plug those in?

**Comment by dkoak** [comment]
Yes, thank you. I had plugged the in the wrong way.

**Comment by Adamkadaban** [comment]
Had the same issue. Just update the versions in the requirements.txt and it should work.

**Comment by spacepirate0001** [comment]
Stay with docker image its running python 3.8 and all the requirements work there

**Comment by absolutbernie** [comment]
i keep getting an error when i install requirement.txt   cant create the numpy wheel. I googled it and nothing works for me 
can anyone help?

**Comment by z6il** [comment]
What work with me is delete the update specification in pandas and numpy inside requirement.txt
